// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShisaKanjiDatabaseContext;

namespace DatabaseContext.Migrations
{
    [DbContext(typeof(KanjiDbContext))]
    partial class KanjiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ShisaKanjiDatabaseContext.Models.Kanji", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnName("character")
                        .HasColumnType("VARCHAR(5)");

                    b.HasKey("Id")
                        .HasName("pkey_kanjis");

                    b.HasIndex("Character")
                        .IsUnique()
                        .HasName("idx_kanjis_character");

                    b.ToTable("kanjis");
                });

            modelBuilder.Entity("ShisaKanjiDatabaseContext.Models.Part", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<long>("KanjiId")
                        .HasColumnName("kanji");

                    b.Property<long>("PartialKanjiId")
                        .HasColumnName("part");

                    b.HasKey("Id")
                        .HasName("pkey_parts");

                    b.HasIndex("PartialKanjiId");

                    b.HasIndex("KanjiId", "PartialKanjiId")
                        .IsUnique()
                        .HasName("idx_parts_kanji_part");

                    b.ToTable("parts");
                });

            modelBuilder.Entity("ShisaKanjiDatabaseContext.Models.Structure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<long>("KanjiId")
                        .HasColumnName("kanji");

                    b.Property<string>("Note")
                        .HasColumnName("note")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("StructureString")
                        .IsRequired()
                        .HasColumnName("structure")
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id")
                        .HasName("pkey_structures");

                    b.HasIndex("KanjiId", "StructureString")
                        .IsUnique()
                        .HasName("idx_structures_kanji_structure");

                    b.ToTable("structures");
                });

            modelBuilder.Entity("ShisaKanjiDatabaseContext.Models.Part", b =>
                {
                    b.HasOne("ShisaKanjiDatabaseContext.Models.Kanji", "Kanji")
                        .WithMany("MinorParts")
                        .HasForeignKey("KanjiId")
                        .HasConstraintName("fkey_parts_kanji")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShisaKanjiDatabaseContext.Models.Kanji", "PartialKanji")
                        .WithMany("MajorParts")
                        .HasForeignKey("PartialKanjiId")
                        .HasConstraintName("fkey_parts_part")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShisaKanjiDatabaseContext.Models.Structure", b =>
                {
                    b.HasOne("ShisaKanjiDatabaseContext.Models.Kanji", "Kanji")
                        .WithMany("Structures")
                        .HasForeignKey("KanjiId")
                        .HasConstraintName("fkey_structures_kanji")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
